# Sylva Engine Configuration File
# Generated on 2025-05-03 15:00:44

assetPath = assets
mouseSensitivity = 0.100000
windowWidth = 1280
windowHeight = 720
windowTitle = Sylva Engine
fullscreen = false
vsync = true
