# Sylva Engine Configuration File
# Generated on 2025-05-03 15:00:44

assetPath = assets
mouseSensitivity = 0.100000
windowWidth = 1920
windowHeight = 1080
windowTitle = Sylva
fullscreen = false
vsync = true
